version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  production:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - add_ssh_keys:
          fingerprints:
            - "35:1e:5e:0a:95:ec:f3:3e:79:7b:b4:39:ac:00:5f:b2"
      - run: 
          name: update demo app on production server
          command: |
            ssh ubuntu@ssh.supertokens.io '\
              cd /home/ubuntu/supertokens-demo-react-thirdpartyemailpassword && \
              git reset --hard && \
              git checkout thirdpartyemailpassword && \
              git pull && \
              rm package-lock.json && \
              rm -rf node_modules && \
              npm i && \
              REACT_APP_API_PORT=10001 REACT_APP_API_URL=https://api-thirdpartyemailpassword.demo.supertokens.io REACT_APP_WEBSITE_PORT=10000 REACT_APP_WEBSITE_URL=https://thirdpartyemailpassword.demo.supertokens.io npm run build && \
              docker rm demo-app-thirdpartyemailpassword -f || true && \
              bash /home/ubuntu/supertokens-demo-react-thirdpartyemailpassword/scripts/start_container.sh'
      - slack/status
workflows:
  version: 2
  tagged-build:
    jobs:
      - production:
          context:
            - slack-notification
          filters:
            tags:
              only: /(\d\d\-\d\d\-\d\d\d\d\-\-\d\d\-\d\d\-\d\d)/
            branches:
              ignore: /.*/